name: CD
on:
  push:
    tags:
      - '*'
    branches:
      - fix-cd-workflow

## -- The build jobs --
## ![ NOTE ] The build job that uses a strategy matrix gets queued indefinitely.
## To resolve this issue, we can split the jobs into separate jobs for each operating system.
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          path: |
            out/**/*.deb
            out/**/*.rpm
          name: Kommita-${{ github.ref_name }}-linux-${{ github.sha }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          path: |
            out/**/*.zip
          name: Kommita-${{ github.ref_name }}-macos-${{ github.sha }}
  #
  #  build-windows:
  #    runs-on: windows-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - uses: actions/setup-node@v4
  #        with:
  #          node-version: '22'
  #      - run: npm ci
  #      - run: npm run make
  #      - uses: actions/upload-artifact@v4
  #        with:
  #          name: Kommita-${{ github.ref_name }}-windows-${{ github.sha }}
  #          path: out

  release:
    runs-on: ubuntu-latest
    needs: [ build-linux, build-macos ]
    #    needs: [ build-linux, build-macos, build-windows ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: out/
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            out/**/*.deb
            out/**/*.rpm
            out/**/*.zip
          tag_name: 0.0.0.0
        #          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
