name: CD
on: [ push ]

jobs:
  build:
    runs-on: ${ { matrix.os } }
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v4

#jobs:
#  build:
#    runs-on: ${ { matrix.os } }
#    strategy:
#      matrix:
#        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '22'
#      - run: npm ci
#      - run: npm run make
#      - uses: actions/upload-artifact@v4
#        with:
#          name: ${event.repository.name}-${{ matrix.os }}-${{ github.sha }}
#          path: /out
