name: CD
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: ${{event.repository.name}}-${{ github.sha }}
          path: out

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: out/
      - uses: softprops/action-gh-release@v2
        with:
          files: out/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
